nameOverride: "vm"
argocdReleaseOverride: "victoria-metrics"
defaultRules:
  create: false
vmsingle:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - vmsingle2.home.lab
vmagent:
  enabled: true
  externalLabels:
    cluster: home-test-cluster
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - vmagent2.home.lab
