apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://victoriametrics.github.io/helm-charts/'
      targetRevision: 0.22.1
      helm:
        valueFiles:
        - $values/observability/victoriametrics-k8s-stack/values/values.yaml
        - $values/observability/victoriametrics-k8s-stack/values/grafana.yaml
      chart: victoria-metrics-k8s-stack
    - repoURL: 'https://github.com/cemehov/argocd-demo2.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true